/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oqs_KEMs */

#ifndef _Included_oqs_KEMs
#define _Included_oqs_KEMs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oqs_KEMs
 * Method:    max_number_KEMs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_oqs_KEMs_max_1number_1KEMs
  (JNIEnv *, jclass);

/*
 * Class:     oqs_KEMs
 * Method:    is_KEM_enabled
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_oqs_KEMs_is_1KEM_1enabled
  (JNIEnv *, jclass, jstring);

/*
 * Class:     oqs_KEMs
 * Method:    get_KEM_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_oqs_KEMs_get_1KEM_1name
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
