/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oqs_KeyEncapsulation */

#ifndef _Included_oqs_KeyEncapsulation
#define _Included_oqs_KeyEncapsulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oqs_KeyEncapsulation
 * Method:    create_KEM_new
 * Signature: (Ljava/lang/String;)Loqs/KeyEncapsulation/KeyEncapsulationDetails;
 */
JNIEXPORT jobject JNICALL Java_oqs_KeyEncapsulation_create_1KEM_1new
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
