/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oqs_KEMs */

#ifndef _Included_oqs_KEMs
#define _Included_oqs_KEMs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oqs_KEMs
 * Method:    max_number_KEMs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_oqs_KEMs_max_1number_1KEMs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
