/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openquantumsafe_KeyEncapsulation */

#ifndef _Included_org_openquantumsafe_KeyEncapsulation
#define _Included_org_openquantumsafe_KeyEncapsulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openquantumsafe_KeyEncapsulation
 * Method:    create_KEM_new
 * Signature: (Ljava/lang/String;)Lsrc/java/KeyEncapsulation/KeyEncapsulationDetails;
 */
JNIEXPORT jobject JNICALL Java_org_openquantumsafe_KeyEncapsulation_create_1KEM_1new
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
