/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_java_oqs_KeyEncapsulation_KeyEncapsulationDetails */

#ifndef _Included_src_java_oqs_KeyEncapsulation_KeyEncapsulationDetails
#define _Included_src_java_oqs_KeyEncapsulation_KeyEncapsulationDetails
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
