/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_java_oqs_KeyEncapsulation */

#ifndef _Included_src_java_oqs_KeyEncapsulation
#define _Included_src_java_oqs_KeyEncapsulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_java_oqs_KeyEncapsulation
 * Method:    create_KEM_new
 * Signature: (Ljava/lang/String;)Lsrc/java/KeyEncapsulation/KeyEncapsulationDetails;
 */
JNIEXPORT jobject JNICALL Java_src_java_oqs_KeyEncapsulation_create_1KEM_1new
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
